# -*- coding: utf-8 -*-
"""taşkağıtmakas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UETWmOTjv3bzwCLtKZvlcUvBpmCE2aC1
"""

import random
raund=int(input("*how many rounds you want to play? "))
actions=("rock","paper","scissor")
c_score=0
your_score=0
Tie=0
for i in range(raund):
    index= random.randint(0,2)
    print(i+1,")","rock,paper or scissor? ")
    you=input().lower()
    if you in actions:
      if you==actions[index]:
         print( "Tie!")
         Tie+=1
         print(" ")
      elif you=="rock" and actions[index]=="scissor":
         print("computer choose: ",actions[index])
         print("you won!")
         your_score+=1
         print(" ")
      elif you=="paper" and actions[index]=="rock":
         print("computer choose: ",actions[index])
         print("you won!")
         your_score+=1
         print(" ")
      elif you=="scissor" and actions[index]=="paper":
         print("computer choose: ",actions[index])
         print("you won!")
         your_score+=1
         print(" ")
      else:
         print("computer choose: ",actions[index])
         print("computer won :(")
         c_score+=1
         print(" ")
    else:
       print("wrong choice,be careful :( ")
       your_score-=1
       c_score+=1
       print(" ")
print("your score:", your_score, "\ncomputer:", c_score,"\nTie:",Tie)

